# Generated by Django 5.2.17 on 2026-09-01 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Betankande',
            fields=[
                ('dok_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('rm', models.CharField(db_index=True, max_length=16)),
                ('beteckning', models.CharField(db_index=True, max_length=32)),
                ('titel', models.CharField(blank=True, max_length=400)),
                ('organ', models.CharField(blank=True, max_length=16)),
                ('datum', models.DateField(blank=True, null=True)),
                ('notis', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ledamot',
            fields=[
                ('intressent_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('sourceid', models.CharField(blank=True, max_length=64)),
                ('tilltalsnamn', models.CharField(max_length=120)),
                ('efternamn', models.CharField(max_length=120)),
                ('sorteringsnamn', models.CharField(db_index=True, max_length=240)),
                ('parti', models.CharField(db_index=True, max_length=8)),
                ('valkrets', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(blank=True, max_length=160)),
                ('kon', models.CharField(blank=True, max_length=16)),
                ('fodd_ar', models.PositiveIntegerField(blank=True, null=True)),
                ('bild_url', models.URLField(blank=True)),
                ('bild_url_liten', models.URLField(blank=True)),
                ('epost', models.CharField(blank=True, max_length=160)),
                ('titel', models.CharField(blank=True, max_length=160)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('antal_voteringar', models.PositiveIntegerField(default=0)),
                ('antal_franvarande', models.PositiveIntegerField(default=0)),
                ('antal_med_partiet', models.PositiveIntegerField(default=0)),
                ('antal_mot_partiet', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sorteringsnamn'],
            },
        ),
        migrations.CreateModel(
            name='Votering',
            fields=[
                ('votering_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('rm', models.CharField(db_index=True, max_length=16)),
                ('beteckning', models.CharField(db_index=True, max_length=32)),
                ('punkt', models.PositiveIntegerField(default=1)),
                ('dok_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('datum', models.DateField(blank=True, db_index=True, null=True)),
                ('avser', models.CharField(blank=True, max_length=40)),
                ('titel', models.CharField(blank=True, max_length=400)),
                ('ja', models.PositiveIntegerField(default=0)),
                ('nej', models.PositiveIntegerField(default=0)),
                ('avstar', models.PositiveIntegerField(default=0)),
                ('franvarande', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-datum', 'beteckning', 'punkt'],
            },
        ),
        migrations.CreateModel(
            name='Uppdrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_kod', models.CharField(max_length=32)),
                ('organ_namn', models.CharField(blank=True, max_length=160)),
                ('roll', models.CharField(max_length=80)),
                ('typ', models.CharField(blank=True, max_length=40)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('ledamot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uppdrag', to='riksdag.ledamot')),
            ],
            options={
                'ordering': ['organ_kod', 'roll'],
            },
        ),
        migrations.CreateModel(
            name='Rost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intressent_id', models.CharField(db_index=True, max_length=32)),
                ('namn', models.CharField(max_length=160)),
                ('parti', models.CharField(db_index=True, max_length=8)),
                ('rost', models.CharField(max_length=16)),
                ('med_partiet', models.BooleanField(null=True)),
                ('ledamot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster', to='riksdag.ledamot')),
                ('votering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='riksdag.votering')),
            ],
            options={
                'indexes': [models.Index(fields=['ledamot', 'rost'], name='riksdag_ros_ledamot_276e1c_idx'), models.Index(fields=['votering', 'parti'], name='riksdag_ros_voterin_f452f8_idx')],
                'constraints': [models.UniqueConstraint(fields=('votering', 'intressent_id'), name='unique_rost')],
            },
        ),
        migrations.CreateModel(
            name='PartiLinje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parti', models.CharField(max_length=8)),
                ('linje', models.CharField(blank=True, max_length=16)),
                ('votering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partilinjer', to='riksdag.votering')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('votering', 'parti'), name='unique_partilinje')],
            },
        ),
    ]
